### ISSUE TITLE
User experience wanted

### ISSUE THREAD

**Issue by FilipDominec** [philoteer/rp2daq_setup#1]
Hi, thanks for testing rp2daq!

I stumbled upon this repo and wanted to ask if there is anything I can do for newcomers to install rp2daq a convenient way.

What, in an ideal world, should rp2daq project install like? Is setuptools & pypi the way to go? 

Yesterday I released a fairly optimized version on github, so it certainly could be put on pypi too. Any tips are appreciated.

**Comment by philoteer** [comment]
Hello. Thank you for making and maintaining rp2daq.

I did this mostly because I wanted to use rp2daq with GNU Radio, which generates and executes Python codes for signal processing purposes. There are other workarounds (like manually copying the libraries into a Python PATH), but I thought this would be a better idea (except that I did not quite understand Python setuptools, so I kinda messed that up). 

I think having an installable package is beneficial in some use cases, like mine or for some deployment scenarios (when I want to just call "import rp2daq" without moving around files). But then, maybe it can confuse some newcomers if it does not guide them through the firmware installation..

**Comment by FilipDominec** [comment]
So would you personally prefer installing it through ```pip install rp2daq```, with a well visible notice about where to get the firmware and how to upload it? 

I can certainly do it, but it adds some extra complexity to the project. Or I can keep it just in the github repo, with a manual download option. Both is fine from my POV, but I am the dev. This is why user opinion matters to me.

**Comment by philoteer** [comment]
I personally prefer the former option, but the latter is fine too. Both work for me (not a major issue, to me). 

Maybe it can be left in a low-priority wishlist (in my opinion), since it would definitely take some efforts.

**Comment by FilipDominec** [comment]
OK, thanks.
